FROM node:23-slim

WORKDIR /app

ENV NODE_ENV=development

COPY package*.json ./
RUN npm install

# For testing
RUN apt-get update && apt-get install -y curl dnsutils iputils-ping

RUN npm install -g nodemon

COPY . .

EXPOSE 5001

CMD ["npx", "nodemon", "src/server.js"]