FROM node:23-slim

WORKDIR /app

ENV NODE_ENV=development

# Step 1: Copy only package.jsons so Docker can cache npm installs
COPY backend/package*.json ./backend/
COPY backend/server/package*.json ./backend/server/
COPY backend/authentication_server/package*.json ./backend/authentication_server/

# Step 2: Install all dependencies
RUN cd backend && npm install
RUN cd backend/server && npm install
RUN cd backend/authentication_server && npm install

RUN npm install -g concurrently

# Step 3: Now copy full backend source
COPY backend ./backend

# Step 4: Set up server
WORKDIR /app/backend

EXPOSE 5001 4000

CMD ["npm", "run", "dev"]
