### Add user

POST http://localhost:3000/api/user
Content-Type: application/json

{
    "name": "user2",
    "email": "user2@gmail.com",
    "number": "+3583242124",
    "password": "Salasan4_"
}

### Login user

POST http://localhost:4000/api/login
Content-Type: application/json

{
    "username": "user2",
    "password": "Salasan4_"
}

### Logout user

DELETE http://localhost:4000/api/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6IlRvbWkgS2FydGFzbGFtbWkiLCJpYXQiOjE3NDM2Njc2MTl9.zs1TosEYgPRZLaxrlc68WT8Dwpnr8lKVHaam-qenIGo"
}

### Google sign in

GET http://localhost:4000/api/googleauth

### Get users

GET http://localhost:3000/api/users

### Delete user

DELETE http://localhost:3000/api/user/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6IlRvbWkgS2FydGFzbGFtbWkiLCJpYXQiOjE3NDM2Njc0ODgsImV4cCI6MTc0MzY3MTA4OH0.6Po11mMi0waT75NalcJ_YHySplFE4yw2jGUYSNqj2xg

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6IlRvbWkgS2FydGFzbGFtbWkiLCJpYXQiOjE3NDM2Njc0ODh9.TTi0kujPUuB6iEFYsOMxVTfFl-dc7RIf70kzE9SnHbM"
}

### Get new refresh token

POST http://localhost:4000/api/token
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywibmFtZSI6InVzZXIzIiwiaWF0IjoxNzQzNTk0MTY5LCJleHAiOjE3NDM1OTc3Njl9.7aKGtTxs2b7Im09jkrM_kVC_3BlgBvMaXpvpmvWrITQ

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6IlRvbWkiLCJpYXQiOjE3NDM0OTQyMjZ9.oo_WhSEbByiOnld44XRbw3mRfd9qsugo_Cs6G7ioC-M"
}

### Send friend request

POST http://localhost:3000/api/friend/request
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6InVzZXIxIiwiaWF0IjoxNzQzNjgwNTYyLCJleHAiOjE3NDM2ODQxNjJ9.HMjdLiGGzH22izfrzEzMLOD0CCUcxoqjjFgtZFH0s1I

{
    "friendId": "2"
}

### Accept friend request

POST http://localhost:3000/api/friend/accept
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibmFtZSI6InVzZXIyIiwiaWF0IjoxNzQzNjgwNjI3LCJleHAiOjE3NDM2ODQyMjd9.3Rh5wmH6T2-IdaKBf-SyiDhjzGN5qx08y-Gr2PQmfSI

{
    "friendId": "1"
}

### Check pending friedn requests

GET http://localhost:3000/api/friend/check_pending
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibmFtZSI6InVzZXIyIiwiaWF0IjoxNzQzNjgwNjI3LCJleHAiOjE3NDM2ODQyMjd9.3Rh5wmH6T2-IdaKBf-SyiDhjzGN5qx08y-Gr2PQmfSI

### Block friend request

POST http://localhost:3000/api/friend/block
Content-Type: application/json
Authorization: Bearer

{
    "friendId": "2"
}

### Find all friends for user

GET http://localhost:3000/api/friends
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6InVzZXIxIiwiaWF0IjoxNzQzNjgwNTYyLCJleHAiOjE3NDM2ODQxNjJ9.HMjdLiGGzH22izfrzEzMLOD0CCUcxoqjjFgtZFH0s1I