### Add user

POST http://localhost:3000/api/user
Content-Type: application/json

{
    "name": "3333",
    "email": "fd@gmail.com",
    "number": "+401234567",
    "password": "Salasan4_"
}

### Login user

POST http://localhost:4000/api/login
Content-Type: application/json

{
    "username": "3333",
    "password": "Salasan4_"
}

### Enable 2FA

POST http://localhost:3000/api/2fa/enable
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibmFtZSI6IjMzMzMiLCJpYXQiOjE3NDM1MTI2MzMsImV4cCI6MTc0MzUxNjIzM30.51HHQLEYZNGPV2lUTuyNMSkSpWUtclxOsyliufWfdFY

{
    "method": "sms"
}

### disable 2FA

POST http://localhost:3000/api/2fa/disable
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6IlRvbWkiLCJpYXQiOjE3NDM0OTQzMDIsImV4cCI6MTc0MzQ5NzkwMn0.y-e5SJZaNsdhOdWXG2Yv9A69WptKSq8Cc9RGPgf5w3w
### Logout user

DELETE http://localhost:4000/api/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6IlRvbWkiLCJpYXQiOjE3NDM0OTQzMDIsImV4cCI6MTc0MzQ5NzkwMn0.y-e5SJZaNsdhOdWXG2Yv9A69WptKSq8Cc9RGPgf5w3w

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6IlRvbWkiLCJpYXQiOjE3NDM0OTQyMjZ9.oo_WhSEbByiOnld44XRbw3mRfd9qsugo_Cs6G7ioC-M"
}

###

POST http://localhost:4000/api/verify/otp
Content-Type: application/json
Authorization: Bearer

{
    "otp": ""
}

### Get users

GET http://localhost:3000/api/users

### Delete user

DELETE http://localhost:3000/api/user/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6IlRvbWkiLCJpYXQiOjE3NDM0OTQzMDIsImV4cCI6MTc0MzQ5NzkwMn0.y-e5SJZaNsdhOdWXG2Yv9A69WptKSq8Cc9RGPgf5w3w

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6IlRvbWkiLCJpYXQiOjE3NDM0OTMzNjd9.0NVG9imcA2XDfnCA5n7fF-wnlKnYgyNlPjA5NxP-ij4"
}

### Get new refresh token

POST http://localhost:4000/api/token
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6IlRvbWkiLCJpYXQiOjE3NDM0OTQyMjYsImV4cCI6MTc0MzQ5NzgyNn0._56Ri3Lbd-M03eDmh9ZMjlRm9LpuadTFdCB59rkDyTs

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6IlRvbWkiLCJpYXQiOjE3NDM0OTQyMjZ9.oo_WhSEbByiOnld44XRbw3mRfd9qsugo_Cs6G7ioC-M"
}