### Add user

POST http://localhost:5001/api/user
Content-Type: application/json

{
    "name": "uusi",
    "email": "uusi@moi.com",
    "password": "Test123!"
}

### Login user

POST http://localhost:4000/api/login
Content-Type: application/json

{
    "email": "testi@moi.com",
    "password": "Test123!"
}

### Logout user

DELETE http://localhost:4000/api/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwibmFtZSI6IlBhdHJpayBMw6VuZyIsImlhdCI6MTc0NDcxNDY4MX0.1X99fxMTIhxhmEU-xXm63U9joj5n9Mmu-sN1m4gzhp0"
}

### Google sign in

GET http://localhost:4000/api/googleauth

### Get users

GET http://localhost:5001/api/users

### Get single user

GET http://localhost:3000/api/user/3

### Delete user

DELETE http://localhost:3000/api/user/delete
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwibmFtZSI6Im1hdHVyZW1vb3NlNTEiLCJpYXQiOjE3NDQ5NzA2ODQsImV4cCI6MTc0NDk3MTU4NH0.sIj7xYW9S_jGU7_3SgLX9fOanbhJhvfYhCkG0Fln5Eo

{
    "id": "8",
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwibmFtZSI6Im1hdHVyZW1vb3NlNTEiLCJpYXQiOjE3NDQ5NzA2ODR9.aorAG4W1Pe6sI-aPehRLf9THyOH8S9ZUs8eFik4Kdis"
}

### Get new refresh token

POST http://localhost:4000/api/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwibmFtZSI6InF1aWNrZXN0Z2F5YWw0MSIsImlhdCI6MTc0NDk2NjAwOH0.ySyZ9TXpekg-HPb127vLtMBNOIy-i_JqOXWCQ-r0Lzk"
}

### Send friend request

POST http://localhost:3000/api/friend/request
Content-Type: application/json
Authorization: Bearer 

{
    "friendId": "2"
}

### Accept friend request

POST http://localhost:3000/api/friend/accept
Content-Type: application/json
Authorization: Bearer 

{
    "friendId": "1"
}

### Check pending friedn requests

GET http://localhost:3000/api/friend/check_pending
Authorization: Bearer 

### Block friend request

POST http://localhost:3000/api/friend/block
Content-Type: application/json
Authorization: Bearer

{
    "friendId": "2"
}

### Find all friends for user

GET http://localhost:3000/api/friends
Authorization: Bearer ayJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibmFtZSI6InRlc3RpIiwiaWF0IjoxNzQ0Mjc4MDg0LCJleHAiOjE3NDQyODE2ODR9.WoLtOePwlvNheh4llONsIFyjfE71Ik800UmvQ4CRDNc

### Create new tournament

POST http://localhost:3000/api/tournament/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywibmFtZSI6InRlc3RpcyIsImlhdCI6MTc0NTQwODk4NSwiZXhwIjoxNzQ1NDA5ODg1fQ.DKu_Vgi486N7CZKIaqmCyFdT7v30WcqP8zsFFuoIfng

{
    "name": "testiturnaus",
    "size": "2"
}

### Join tournament

POST http://localhost:3000/api/tournament/1/join
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibmFtZSI6InRlc3RpIiwiaWF0IjoxNzQ1NDA5NjQ5LCJleHAiOjE3NDU0MTA1NDl9.KoE6YckcKoiZvKWlcH1SPapkUtZxc_ZdB2V6ghEKAK0

### set player ready

PATCH http://localhost:3000/api/tournament/1/ready
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibmFtZSI6InRlc3RpIiwiaWF0IjoxNzQ1NDA5NjQ5LCJleHAiOjE3NDU0MTA1NDl9.KoE6YckcKoiZvKWlcH1SPapkUtZxc_ZdB2V6ghEKAK0

### Get all tournaments

GET http://localhost:5001/api/tournaments

### Start tournament

POST http://localhost:3000/api/tournament/1/start
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibmFtZSI6InRlc3RpIiwiaWF0IjoxNzQ1NDA5NjQ5LCJleHAiOjE3NDU0MTA1NDl9.KoE6YckcKoiZvKWlcH1SPapkUtZxc_ZdB2V6ghEKAK0

### Check active tournament for user

GET http://localhost:5001/api/tournament/1

### Search for users

GET http:/localhost:5001/api/users/search?query=te