### Add user

POST http://localhost:3000/api/user
Content-Type: application/json

{
    "name": "",
    "email": "",
    "password": ""
}

### Login user

POST http://localhost:4000/api/login
Content-Type: application/json

{
    "username": "",
    "password": ""
}

### Logout user

DELETE http://localhost:4000/api/logout
Content-Type: application/json

{
    "token": ""
}

### Google sign in

GET http://localhost:4000/api/googleauth

### Get users

GET http://localhost:3000/api/users

### Delete user

DELETE http://localhost:3000/api/user/1
Content-Type: application/json
Authorization: Bearer 

{
    "token": ""
}

### Get new refresh token

POST http://localhost:4000/api/token
Content-Type: application/json
Authorization: Bearer 

{
    "token": ""
}

### Send friend request

POST http://localhost:3000/api/friend/request
Content-Type: application/json
Authorization: Bearer 

{
    "friendId": "2"
}

### Accept friend request

POST http://localhost:3000/api/friend/accept
Content-Type: application/json
Authorization: Bearer 

{
    "friendId": "1"
}

### Check pending friedn requests

GET http://localhost:3000/api/friend/check_pending
Authorization: Bearer 

### Block friend request

POST http://localhost:3000/api/friend/block
Content-Type: application/json
Authorization: Bearer

{
    "friendId": "2"
}

### Find all friends for user

GET http://localhost:3000/api/friends
Authorization: Bearer 