### Add user

POST http://localhost:3000/api/user
Content-Type: application/json

{
    "name": "uusi",
    "email": "uusi@moi.com",
    "password": "Test123!"
}

### Login user

POST http://localhost:4000/api/login
Content-Type: application/json

{
    "username": "uusi",
    "password": "Test123!"
}

### Logout user

DELETE http://localhost:4000/api/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibmFtZSI6InRlc3RpIiwiaWF0IjoxNzQ0Mjg0OTc4fQ.QVkNEZHfwyEIX5iftddQX6xoZUcLDjeKP81vDDXa1XA"
}

### Google sign in

GET http://localhost:4000/api/googleauth

### Get users

GET http://localhost:3000/api/users

### Delete user

DELETE http://localhost:3000/api/user/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywibmFtZSI6InRlc3RpcyIsImlhdCI6MTc0NDI4NTQ5MSwiZXhwIjoxNzQ0Mjg5MDkxfQ.TaRTX_v5Qc2k5NOdLDa8p7-OJk_U9vuW8xX1yw-kH9Q

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywibmFtZSI6InRlc3RpcyIsImlhdCI6MTc0NDI4NTQ5MX0.MfZjBYq7CZZ623Z4-yWDWaCXwOXOlVWf3j1Y-y51U0Y"
}

### Get new refresh token

POST http://localhost:4000/api/token
Content-Type: application/json
Authorization: Bearer 

{
    "token": ""
}

### Send friend request

POST http://localhost:3000/api/friend/request
Content-Type: application/json
Authorization: Bearer 

{
    "friendId": "2"
}

### Accept friend request

POST http://localhost:3000/api/friend/accept
Content-Type: application/json
Authorization: Bearer 

{
    "friendId": "1"
}

### Check pending friedn requests

GET http://localhost:3000/api/friend/check_pending
Authorization: Bearer 

### Block friend request

POST http://localhost:3000/api/friend/block
Content-Type: application/json
Authorization: Bearer

{
    "friendId": "2"
}

### Find all friends for user

GET http://localhost:3000/api/friends
Authorization: Bearer ayJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibmFtZSI6InRlc3RpIiwiaWF0IjoxNzQ0Mjc4MDg0LCJleHAiOjE3NDQyODE2ODR9.WoLtOePwlvNheh4llONsIFyjfE71Ik800UmvQ4CRDNc